import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Sidebar from '@/components/Sidebar';
const inter = Inter({ subsets: ["latin"] });
import ApplicationForm from "@/components/ApplicationForm";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <div className='flex'>
          <div className='hidden md:block h-[100vh]'>
            <Sidebar />
          </div>
          <div className='p-5 w-full md:max-w-[1140px]'>
            {/* Insert ApplicationForm Component Here */}
            <ApplicationForm />
            {/* Render Other Children */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
